const express=require("express")
const router=express.Router()
const {register}=require("../controller/usercontroller")
const {student}=require("../controller/nevercontroller")
const {student1}=require("../controller/neverrcontroller")
const {student2}=require("../controller/neverrrcontroller")
const {products}=require("../controller/Productcontroller")
const{addcat}=require("../controller/addgetcontroller")
const{subget}=require("../controller/subgetcontroller")
const{catdel}=require("../controller/catdelcontroller")
const{subdel}=require("../controller/subdelcontroller")
const{proget}=require("../controller/Productgetcontroller")
const{prodel}=require("../controller/Prodelcontroller")
const{pget}=require("../controller/pgetcontroller")
const{sget}=require("../controller/sgetcontroller")
const {pdetail}=require("../controller/producdetailtcontroller")
const {ProductQuantity}=require("../controller/productquantityupdatecontroller")
const{cardd}=require("../controller/cardcontroller")
const{cadget}=require("../controller/cardgetcontroller")
const{cardupdate}=require("../controller/cardupdatecontroller")
const{cardel}=require("../controller/carddelcontroller")
const {catup}=require("../controller/catupdatecontroller")
const{subup}=require("../controller/addsubupcontroller")
const{proupdate}=require("../controller/ProductUpdatecontroller")
const{check}=require("../controller/checkoutcontroller")
const{fetch}=require("../controller/fetchcontroller")
const {paymentmethod,paymentverify}=require("../controller/payment")
const{orderstatus}=require("../controller/orderstatuscontroller")
const{allorders}=require("../controller/allorderscontroller")
const{recommend,compare}=require("../controller/airecommendcontroller")
router.post("/register",register)
const upload=require("../middleware/upload")
router.post("/login", upload.single("File"),student)
router.post("/student1",student1)
router.post("/student2", upload.single("File"),student2)
router.post("/product",upload.single("File"),products)
router.put("/catup/:catid",upload.single("File"),catup)
router.put("/subup/:catid",upload.single("File"),subup)
router.put("/proupdate/:proid",upload.single("File"),proupdate)

router.get("/addcats",addcat)
router.get("/subget",subget)
router.get("/proget",proget)
router.get("/fetch/:Email",fetch)
router.get("/sget/:catid",sget)
router.get("/pget/:pid",pget)
router.get("/pdetail/:pid",pdetail)
router.delete("/catdel/:id",catdel)
router.delete("/subdel/:id",subdel)
router.delete("/prodel/:id",prodel)
router.put("/ProductQuantity/:id",ProductQuantity)
router.put("/cardupdate/:id",cardupdate)
router.post("/cardd",cardd)
router.get("/cadget/:Email",cadget)
router.delete("/cardel/:id",cardel)
router.post("/check",check)
router.post("/create-checkout-session",paymentmethod)
router.get("/payment-verify/:session_id",paymentverify)
router.put("/orderstatus/:id",orderstatus)
router.get("/allorders",allorders)
router.post("/ai-recommend",recommend)
router.post("/ai-compare",compare)
module.exports=router